### ISSUE TITLE
`KeyError: 'asscalar'` when importing scico

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#374]
The current release of scico on PyPI (the one that `pip install scico` gets, version 0.0.3) seems to run into some compatibility problem with jax. I think this is fixed in the most recent version on github, but it might be worth tracking down.

```
conda create python=3.8 --name temp_scico_pip
pip install scico
python
>>> import scico
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mccann/miniconda3/envs/temp_scico_pip/lib/python3.8/site-packages/scico/__init__.py", line 37, in <module>
    from . import numpy
  File "/Users/mccann/miniconda3/envs/temp_scico_pip/lib/python3.8/site-packages/scico/numpy/__init__.py", line 43, in <module>
    _wrappers.wrap_recursively(vars(), mathematical_functions, _wrappers.map_func_over_blocks)
  File "/Users/mccann/miniconda3/envs/temp_scico_pip/lib/python3.8/site-packages/scico/numpy/_wrappers.py", line 57, in wrap_recursively
    target_dict[name] = wrap(target_dict[name])
KeyError: 'asscalar'
```

**Comment by bwohlberg** [comment]
I think this is the same as #363, but good to have a reminder that we should make sure that the most recent release still works.

**Comment by bwohlberg** [comment]
Closing as resolved by the PyPI release of `0.0.3.post1`.
